.TH koios 1 2016-May "linux" "heatherly custom tools manual"

.SH NAME
koios_polos \- sweet c unit testing metaprogram and mini-language

.SH IMAGERY (see HERITAGE at bottom for more)
northern star (polos), the axis around which all consellations revolve

.SH SUMMARY
koios (pronounced key-oh-s) is a light, clean, simple, and fast c unit testing
metaprogram that reads a scripting mini-language file as input and creates a c
source file to conduct the unit testing as output.

.SH SYNOPSIS

.B koios [BASENAME]
.nf
which is the primary production version

.B koios_debug [URGENTS] [BASENAME]
.nf
which can perform all production actions, but with debugging and tracing

.SH OPTIONS
koios is simple, efficient, and direct, therefore it has a very limited
option set.

.B <basename>
.RS 8
base unit test file name with no ".unit" extention.
.RE

.B --convert
.RS 8
updates the unit test file format to the latest standard.
.RE

.B --unittest
.RS 8
creates the unit testing c source file for later compilation.
.RE


koios only accepts a single option, BASENAME, which is the program to be unit
tested's executable name.  technically, it can be any name, but using it this
way is cleanest and easiest to remember.

.SH FILES
.B [BASENAME].unit
, a 7bit safe, human-readable ascii text file that contains the unit testing
scripts.  its structure is described below in the STRUCTURE section.

.B [BASENAME]_unit.c
, a 7bit safe, human-readable ascii text file contained the resulting
c source code to be linked to your program, compiled, and executed as
described in the COMPILING and EXECUTION sections.


.SH COMPILING
to work properly, the main function of the c program must be placed in
a separate source file.  i call mine by the [BASENAME]_main.c.  the unit
test creates its own main function within [BASENAME]_unit.c.  all program
modules (except main) need to be linked against [BASENAME]_unit.c to create
an executable.  i name the resulting executable [BASENAME]_unit.

.SH EXECUTING
the resulting [BASENAME]_unit executable has several options build in.

.B @@quiet
, no output only a return code : neg = fail, pos = warn, 0 = pass

.B @@test
, only a single line of summary numbers indicating pass/fail

.B --list-scrp
, shows a list of script headers for reference (no execution).

.B <nn> --list-scrp
, with script number it will only show for that script.

.B --list-cond
, shows a list of condition headers for reference (no execution).

.B <nn> --list-cond
, with script number it will only show for that script.

.B --scrp
, shows summary and script level output.  no step details

.B @@cond
, shows summary, script, and condition output. no step details.

.B @@step
, shows summary, script, and condition, and step output. no details.

.B @@full
, shows all output.  this is the default.

.B --console
, show plain text without terminal color codes.

.B --eterm
, show output with embedded eterm, 256 color terminal color codes.

.B <nn>
, two digits with a leading zero if required to make two.  this
causes the unit test to only run the script by that number.

.B <nnn>
, three digits with a leading zeros if required to make three.  this causes
the unit test to only show the condition by that number.  sometimes this
makes it easier to find in the output.

.SH AUTHOR
rsheatherly can be reached at jelloskrike at gmail dot com

.SH HERITAGE
koios-polos (northern axis) is one of the original twelve greek titan-gods and
the archetype of the inquisitive and questioning mind.  when the titans
overthrew the protogenos (primeval gods), koios was the god that held ouranos
(sky) by the northern pole of the world.  koios is the god of the axis of heaven
around which the constellations revolved and of the heavenly oracles.  he was
also husband to phoebe who presided over the earth oracles.

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster
